
export const products = [
  {
    id: 'p1',
    name: 'Samsung Galaxy S24 Ultra',
    category: 'electronics',
    brand: 'Samsung',
    price: 1199,
    rating: 4.9,
    color: 'Titanium Gray',
    size: '512GB',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
    features: ['Galaxy AI', 'S Pen Included', '200MP Camera', 'Snapdragon 8 Gen 3'],
    description: 'The ultimate flagship phone with built-in AI for enhanced productivity and creativity.',
    dna: { tech: 95, style: 80, utility: 90 },
    prompt: 'Professional studio shot of Samsung Galaxy S24 Ultra, titanium gray, cinematic lighting, 8k resolution, sleek design'
  },
  {
    id: 'p2',
    name: 'Sony WH-1000XM5 Headphones',
    category: 'electronics',
    brand: 'Sony',
    price: 399,
    rating: 4.8,
    color: 'Silver',
    size: 'Over-ear',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80',
    features: ['Industry Leading ANC', '30-hour Battery', 'Quick Attention Mode', 'Multipoint Connection'],
    description: 'Experience silence like never before with high-fidelity sound and best-in-class noise cancellation.',
    dna: { tech: 90, style: 85, utility: 85 },
    prompt: 'High-end audio headphones Sony WH-1000XM5, silver finish, minimalist background, soft shadows, hyper-realistic'
  },
  {
    id: 'p3',
    name: 'Apple MacBook Pro M3 Max',
    category: 'electronics',
    brand: 'Apple',
    price: 3499,
    rating: 4.9,
    color: 'Space Black',
    size: '14-inch',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
    features: ['M3 Max Chip', 'Liquid Retina XDR', '128GB Unified Memory', 'Up to 22h Battery'],
    description: 'The most powerful laptop for professionals who need extreme performance on the go.',
    dna: { tech: 98, style: 95, utility: 80 },
    prompt: 'Apple MacBook Pro M3 Max space black, open lid, glowing screen, depth of field, premium tech aesthetic'
  },
  {
    id: 'p4',
    name: 'Logitech MX Master 3S',
    category: 'electronics',
    brand: 'Logitech',
    price: 99,
    rating: 4.7,
    color: 'Pale Grey',
    size: 'Standard',
    image: 'https://images.unsplash.com/photo-1631033031072-263562393f9c?w=800&q=80',
    features: ['MagSpeed Scrolling', '8K DPI Tracking', 'Quiet Clicks', 'Flow Cross-Computer Control'],
    description: 'Master your flow with the ultimate ergonomic precision mouse.',
    dna: { tech: 85, style: 75, utility: 98 },
    prompt: 'Ergonomic mouse Logitech MX Master 3S, pale grey, office setup, macro photography, sharp focus'
  },
  {
    id: 'p5',
    name: 'Dyson V15 Detect Absolute',
    category: 'home',
    brand: 'Dyson',
    price: 749,
    rating: 4.6,
    color: 'Yellow/Nickel',
    size: 'Cordless',
    image: 'https://images.unsplash.com/photo-1558317374-067df5f15430?w=800&q=80',
    features: ['Laser Slim Fluffy', 'HEPA Filtration', 'LCD Screen', 'Piezo Sensor'],
    description: 'Intelligently senses and adapts for a deep clean everywhere. Laser reveals hidden dust.',
    dna: { tech: 88, style: 70, utility: 95 },
    prompt: 'Dyson V15 vacuum cleaner, high-tech cleaning device, futuristic design, white studio background, 4k'
  },
  {
    id: 'p6',
    name: 'Philips Hue Starter Kit',
    category: 'home',
    brand: 'Philips',
    price: 199,
    rating: 4.5,
    color: 'RGB',
    size: '3 Bulbs + Bridge',
    image: 'https://images.unsplash.com/photo-1550985543-f47f20421867?w=800&q=80',
    features: ['16 Million Colors', 'Voice Control', 'Automated Schedules', 'Zigbee Hub'],
    description: 'Set the perfect mood for any occasion with smart LED lighting.',
    dna: { tech: 82, style: 90, utility: 75 },
    prompt: 'Philips Hue smart bulbs, vibrant colors, home interior, warm ambient lighting, realistic texture'
  },
  {
    id: 'p7',
    name: 'Nike Air Jordan 1 Retro',
    category: 'clothing',
    brand: 'Nike',
    price: 180,
    rating: 4.9,
    color: 'Chicago Red',
    size: '10',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    features: ['Iconic Design', 'Premium Leather', 'Air Cushioning', 'Rubber Cupsole'],
    description: 'The sneaker that started it all. A must-have for every collector.',
    dna: { tech: 40, style: 99, utility: 60 },
    prompt: 'Nike Air Jordan 1 Chicago, sneaker culture, street photography, urban vibe, vivid colors'
  },
  {
    id: 'p8',
    name: 'Levi\'s 511 Slim Jeans',
    category: 'clothing',
    brand: 'Levi\'s',
    price: 89,
    rating: 4.4,
    color: 'Medium Indigo',
    size: '32x32',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
    features: ['Slim Fit', 'Stretch Denim', 'Sustainable Sourced', 'Classic 5-Pocket'],
    description: 'The perfect modern slim fit that isn\'t too tight.',
    dna: { tech: 10, style: 85, utility: 90 },
    prompt: 'Levis 511 slim jeans, folded on wooden shelf, indigo texture, high quality denim, lifestyle shot'
  },
  {
    id: 'p9',
    name: 'Apple Watch Ultra 2',
    category: 'wearables',
    brand: 'Apple',
    price: 799,
    rating: 4.8,
    color: 'Natural Titanium',
    size: '49mm',
    image: 'https://images.unsplash.com/photo-1544117518-2b462f587b12?w=800&q=80',
    features: ['Action Button', 'Dual-Frequency GPS', '36-hour Battery', 'Ocean Band'],
    description: 'The most rugged and capable Apple Watch ever, designed for athletes and adventurers.',
    dna: { tech: 94, style: 88, utility: 92 },
    prompt: 'Apple Watch Ultra 2, titanium body, orange alpine loop, rugged environment, macro shot'
  },
  {
    id: 'p10',
    name: 'KitchenAid Artisan Stand Mixer',
    category: 'kitchen',
    brand: 'KitchenAid',
    price: 449,
    rating: 4.9,
    color: 'Candy Apple Red',
    size: '5-Quart',
    image: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=800&q=80',
    features: ['10 Speeds', 'Tilt-Head Design', 'Power Hub', 'Stainless Bowl'],
    description: 'A kitchen staple for baking enthusiasts, built to last and look great.',
    dna: { tech: 20, style: 95, utility: 95 },
    prompt: 'KitchenAid Artisan stand mixer red, flour dust, baking setup, cozy kitchen, warm lighting'
  },
  {
    id: 'p11',
    name: 'Sony A7 IV Mirrorless Camera',
    category: 'electronics',
    brand: 'Sony',
    price: 2499,
    rating: 4.8,
    color: 'Black',
    size: 'Full Frame',
    image: 'https://images.unsplash.com/photo-1516724562728-afc824a36e84?w=800&q=80',
    features: ['33MP Sensor', '4K 60p Video', 'Real-time Eye AF', '5-axis Stabilization'],
    description: 'The hybrid camera for modern creators, balancing high-res stills and professional video.',
    dna: { tech: 96, style: 75, utility: 88 },
    prompt: 'Sony A7IV camera with lens, professional photography gear, bokeh background, cinematic'
  },
  {
    id: 'p12',
    name: 'Herman Miller Aeron Chair',
    category: 'home',
    brand: 'Herman Miller',
    price: 1695,
    rating: 4.9,
    color: 'Graphite',
    size: 'B',
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80',
    features: ['Pellicle Suspension', 'PostureFit SL', 'Adjustable Arms', 'Eco-friendly'],
    description: 'The gold standard for ergonomic office seating, designed for long-term health.',
    dna: { tech: 40, style: 85, utility: 100 },
    prompt: 'Herman Miller Aeron chair, office interior, ergonomic design, luxury workspace, soft light'
  },
  {
    id: 'p13',
    name: 'Nespresso Vertuo Next',
    category: 'kitchen',
    brand: 'Nespresso',
    price: 179,
    rating: 4.3,
    color: 'Dark Grey',
    size: 'Single Serve',
    image: 'https://images.unsplash.com/photo-1517668222347-f5956534bc14?w=800&q=80',
    features: ['Centrifusion Tech', 'App Connectivity', 'Sustainability Program', 'Fast Heat Up'],
    description: 'Coffee and espresso at the touch of a button, delivered in a compact design.',
    dna: { tech: 70, style: 80, utility: 90 },
    prompt: 'Nespresso Vertuo Next machine, steaming coffee cup, morning light, modern kitchen, 4k'
  },
  {
    id: 'p14',
    name: 'Adidas Terrex Free Hiker 2.0',
    category: 'clothing',
    brand: 'Adidas',
    price: 200,
    rating: 4.7,
    color: 'Wonder Beige',
    size: '11',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    features: ['GORE-TEX Lining', 'Boost Midsole', 'Continental Rubber Outsole', 'Sustainable Materials'],
    description: 'Tackle any trail with ultimate comfort and waterproof protection.',
    dna: { tech: 50, style: 75, utility: 98 },
    prompt: 'Adidas Terrex hiking boots, mountain trail background, rugged terrain, outdoor adventure'
  },
  {
    id: 'p15',
    name: 'Nintendo Switch OLED',
    category: 'electronics',
    brand: 'Nintendo',
    price: 349,
    rating: 4.8,
    color: 'White',
    size: '7-inch Screen',
    image: 'https://images.unsplash.com/photo-1578303372216-814059cf157d?w=800&q=80',
    features: ['OLED Display', 'Wide Kickstand', 'Enhanced Audio', '64GB Storage'],
    description: 'Play at home on the TV or on-the-go with a vibrant 7-inch OLED screen.',
    dna: { tech: 80, style: 85, utility: 95 },
    prompt: 'Nintendo Switch OLED white, handheld mode, Zelda gameplay, bright screen, clean shot'
  },
  {
    id: 'p16',
    name: 'Lululemon Align High-Rise Pant',
    category: 'clothing',
    brand: 'Lululemon',
    price: 98,
    rating: 4.9,
    color: 'Black',
    size: '4',
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
    features: ['Nulu Fabric', 'Buttery Soft', 'Hidden Pocket', 'High Rise'],
    description: 'Lightweight, buttery-soft yoga pants that feel like a second skin.',
    dna: { tech: 30, style: 90, utility: 88 },
    prompt: 'Lululemon leggings, yoga studio, athletic lifestyle, high resolution fabric texture'
  },
  {
    id: 'p17',
    name: 'Kindle Paperwhite (16 GB)',
    category: 'books',
    brand: 'Amazon',
    price: 149,
    rating: 4.7,
    color: 'Black',
    size: '6.8-inch',
    image: 'https://images.unsplash.com/photo-1592492159418-39f319320569?w=800&q=80',
    features: ['Adjustable Warm Light', 'IPX8 Waterproof', 'Up to 10 Weeks Battery', 'USB-C Charging'],
    description: 'Purpose-built for reading, with a flush-front design and 300 ppi glare-free display.',
    dna: { tech: 75, style: 60, utility: 95 },
    prompt: 'Kindle Paperwhite, beach setting, reading book, sunlight reflections, water resistant'
  },
  {
    id: 'p18',
    name: 'Razer BlackWidow V4 Pro',
    category: 'electronics',
    brand: 'Razer',
    price: 229,
    rating: 4.6,
    color: 'Black',
    size: 'Mechanical',
    image: 'https://images.unsplash.com/photo-1626952870347-194165d381eb?w=800&q=80',
    features: ['Green Switches', 'Razer Chroma RGB', 'Command Dial', 'Magnetic Wrist Rest'],
    description: 'The ultimate mechanical gaming keyboard, now with even more control and immersion.',
    dna: { tech: 92, style: 95, utility: 85 },
    prompt: 'Razer BlackWidow V4 Pro, glowing RGB, dark gaming room, keyboard macro, neon lights'
  },
  {
    id: 'p19',
    name: 'Theragun PRO G5',
    category: 'fitness',
    brand: 'Therabody',
    price: 599,
    rating: 4.8,
    color: 'Black',
    size: 'Professional',
    image: 'https://images.unsplash.com/photo-1544006659-f0b21f04cb1d?w=800&q=80',
    features: ['QuietForce Tech', 'OLED Screen', 'Customizable Speed', '16mm Amplitude'],
    description: 'The most powerful percussive therapy device for athletic recovery and pain relief.',
    dna: { tech: 85, style: 75, utility: 96 },
    prompt: 'Theragun PRO in gym, recovery tools, professional sport gear, black matte finish'
  },
  {
    id: 'p20',
    name: 'Bose Smart Soundbar 900',
    category: 'electronics',
    brand: 'Bose',
    price: 899,
    rating: 4.7,
    color: 'Arctic White',
    size: 'Dolby Atmos',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
    features: ['Dolby Atmos', 'Voice Control', 'ADAPTiQ Calibration', 'HDMI eARC'],
    description: 'The most immersive Bose soundbar for all your content, with theater-like sound.',
    dna: { tech: 90, style: 92, utility: 80 },
    prompt: 'Bose Soundbar 900 white, living room setup, minimalist design, premium home theater'
  }
];

export const user = {
  id: 'u-777',
  name: 'Arun Kumar',
  displayName: 'Arun',
  location: 'Chennai, Tamil Nadu',
  coordinates: [13.0827, 80.2707],
  loyalty: {
    points: 12450,
    tier: 'Platinum',
    nextTier: 'Diamond',
    progress: 75
  },
  history: [
    { productId: 'p1', date: '2026-03-24', price: 1199 },
    { productId: 'p2', date: '2026-02-15', price: 399 },
    { productId: 'p4', date: '2025-12-10', price: 99 },
    { productId: 'p12', date: '2025-11-05', price: 1695 },
    { productId: 'p3', date: '2025-10-20', price: 3499 },
    { productId: 'p9', date: '2025-08-14', price: 799 },
    { productId: 'p17', date: '2025-06-03', price: 149 }
  ],
  preferences: {
    categories: ['electronics', 'home', 'fitness'],
    styles: ['minimalist', 'tech-focused', 'premium'],
    colors: ['gray', 'black', 'navy']
  },
  wishlist: ['p11', 'p18', 'p19'],
  cart: [
    { productId: 'p13', quantity: 1 }
  ],
  recentlyViewed: ['p20', 'p15', 'p10', 'p5']
};

export const orders = [
  {
    id: 'ord-9921',
    date: '2026-03-24',
    status: 'Delivered',
    items: [{ productId: 'p1', quantity: 1, price: 1199 }],
    total: 1199,
    tracking: 'DEL-CH-001'
  },
  {
    id: 'ord-8845',
    date: '2026-02-15',
    status: 'Delivered',
    items: [{ productId: 'p2', quantity: 1, price: 399 }],
    total: 399,
    tracking: 'DEL-CH-992'
  }
];

export const categories = [
  { id: 'electronics', name: 'Electronics', icon: 'Cpu', color: '#3b82f6' },
  { id: 'home', name: 'Home & Living', icon: 'Home', color: '#10b981' },
  { id: 'clothing', name: 'Fashion', icon: 'Shirt', color: '#f59e0b' },
  { id: 'kitchen', name: 'Kitchen', icon: 'Coffee', color: '#ef4444' },
  { id: 'wearables', name: 'Wearables', icon: 'Watch', color: '#8b5cf6' },
  { id: 'fitness', name: 'Fitness', icon: 'Dumbbell', color: '#ec4899' },
  { id: 'books', name: 'Books', icon: 'BookOpen', color: '#6366f1' }
];

export const realities = [
  { id: 'physical', name: 'Physical World', theme: 'classic', description: 'Standard high-fidelity e-commerce experience.' },
  { id: 'metaverse', name: 'Metaverse Store', theme: 'neon', description: 'Immersive 3D showroom for digital exploration.' },
  { id: 'holographic', name: 'Holographic mode', theme: 'glass', description: 'Floating interfaces and holographic product previews.' },
  { id: 'neural', name: 'Neural Realm', theme: 'abstract', description: 'Thought-controlled shopping simulation (BCI Mock).' }
];
